"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def _require_scitex_dev() -> None:
    """Skip the caller if scitex-dev is not installed on PATH."""
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )


def test_audit_all_clean_for_scitex_config_runs_without_raising():
    # Arrange
    _require_scitex_dev()
    from scitex_dev.testing import audit_all_for_package

    completed = False
    # Act
    audit_all_for_package("scitex-config")
    completed = True
    # Assert
    assert completed
